/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "primary-fixed-dim": "#6366f1",
        "surface-container-low": "#2a2a2a",
        "secondary-fixed-dim": "#4f46e5",
        "on-primary-fixed-variant": "#e0e7ff",
        "error": "#cf6679",
        "tertiary-container": "#4a1d1d",
        "secondary": "#818cf8",
        "surface-tint": "#6366f1",
        "on-secondary-fixed": "#000000",
        "inverse-on-surface": "#121212",
        "background": "#121212",
        "on-tertiary-fixed-variant": "#ffb4ab",
        "surface": "#121212",
        "tertiary-fixed": "#ffdad6",
        "surface-variant": "#2c2c2c",
        "surface-bright": "#1e1e1e",
        "surface-container-lowest": "#000000",
        "tertiary-fixed-dim": "#ffb4ab",
        "on-tertiary": "#000000",
        "on-surface-variant": "#a1a1aa",
        "secondary-fixed": "#e0e7ff",
        "outline-variant": "#3f3f46",
        "outline": "#71717a",
        "on-error": "#000000",
        "on-error-container": "#ffdad6",
        "surface-container-highest": "#333333",
        "inverse-primary": "#4338ca",
        "primary-fixed": "#e0e7ff",
        "primary-container": "#4338ca",
        "surface-dim": "#0a0a0a",
        "on-primary-fixed": "#000000",
        "on-tertiary-fixed": "#310001",
        "on-secondary": "#000000",
        "on-secondary-container": "#e0e7ff",
        "tertiary": "#ffb4ab",
        "on-secondary-fixed-variant": "#3730a3",
        "on-background": "#e4e4e7",
        "surface-container-high": "#2c2c2c",
        "on-tertiary-container": "#ffdad6",
        "on-primary-container": "#e0e7ff",
        "error-container": "#93000a",
        "on-surface": "#e4e4e7",
        "secondary-container": "#3730a3",
        "inverse-surface": "#e4e4e7",
        "on-primary": "#ffffff",
        "surface-container": "#1e1e1e",
        "primary": "#6366F1"
      },
      fontFamily: {
        "headline": ["Inter"],
        "body": ["Inter"],
        "label": ["JetBrains Mono"]
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem"
      },
    },
  },
  plugins: [],
}
